/**
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. OpenMRS is also distributed under
 * the terms of the Healthcare Disclaimer located at http://openmrs.org/license.
 *
 * Copyright (C) OpenMRS Inc. OpenMRS is a registered trademark and the OpenMRS
 * graphic logo is a trademark of OpenMRS Inc.
 */
package org.openmrs.module.chartsearchai.api;

import java.util.Date;
import java.util.List;
import java.util.function.Consumer;

import org.openmrs.Patient;
import org.openmrs.module.chartsearchai.ChartSearchAiConstants;
import org.openmrs.module.chartsearchai.ChartSearchAiUtils;
import org.openmrs.module.chartsearchai.reference.PairChipExtent;
import org.openmrs.module.chartsearchai.reference.SafetyWarning;

/**
 * Answers natural language questions about a patient's chart using an LLM.
 *
 * <p>How the prompt's chart context is assembled is decided by {@code chartsearchai.chartMode}
 * (default {@code queryScoped} — a query-scoped slice, not the whole chart) and, within
 * {@code fullChart}, by {@code chartsearchai.embedding.preFilter} (default {@code false}), which
 * appends a similarity focus hint rather than narrowing anything. {@link ChartAnswer#getSearchMode()}
 * reports which of the three produced a given answer. This paragraph replaced one that described a
 * default-on pre-filter narrowing the chart — machinery removed with the querystore migration
 * (issue #51) and a default that has been {@code false} since before it; the correction belongs with
 * issue #178, which is what a reader trusting the old sentence would have got wrong.
 */
public interface ChartSearchService {

	/**
	 * Search a patient's chart using a natural language question.
	 *
	 * @param patient the patient whose chart to query
	 * @param question the clinician's natural language question
	 * @return the answer with source references for citation linking
	 */
	ChartAnswer search(Patient patient, String question);

	/**
	 * Streaming variant of {@link #search}. Calls the tokenConsumer for each token as
	 * it is generated by the LLM, then returns the complete answer with references.
	 *
	 * @param patient the patient whose chart to query
	 * @param question the clinician's natural language question
	 * @param tokenConsumer called with each token fragment as it is generated
	 * @return the complete answer with source references
	 */
	ChartAnswer searchStreaming(Patient patient, String question, Consumer<String> tokenConsumer);

	/**
	 * Streaming variant that additionally forwards the model's reasoning (chain-of-thought) to
	 * {@code reasoningConsumer} as it is generated, so a caller can surface it as a live "thinking"
	 * indicator. The answer stream to {@code tokenConsumer} is unchanged. Default implementation
	 * ignores reasoning and delegates to the three-arg variant, so existing implementations and
	 * callers are unaffected.
	 *
	 * @param patient the patient whose chart to query
	 * @param question the clinician's natural language question
	 * @param tokenConsumer called with each answer-text fragment as it is generated
	 * @param reasoningConsumer called with each reasoning-text fragment as it is generated
	 * @return the complete answer with source references
	 */
	default ChartAnswer searchStreaming(Patient patient, String question, Consumer<String> tokenConsumer,
			Consumer<String> reasoningConsumer) {
		return searchStreaming(patient, question, tokenConsumer);
	}

	/**
	 * Streaming variant that additionally forwards the answer's citations to {@code citationsConsumer}
	 * the moment the answer is generated — <em>before</em> the citation-grounding pass — so a caller
	 * can render the answer and its clickable citations immediately and let grounding verdicts arrive
	 * afterwards. Grounding (Tier-2 entailment) can add a tail of LLM work; this keeps it off the
	 * path to a readable, cited answer. The returned {@link ChartAnswer} still carries the fully
	 * grounded references. The default ignores {@code citationsConsumer} and delegates to the four-arg
	 * variant, so existing implementations and callers are unaffected.
	 *
	 * @param citationsConsumer called once with the answer's references <em>before</em> grounding
	 *        (verdicts not yet attached); the returned answer carries the grounded references
	 * @return the complete answer with grounded source references
	 */
	default ChartAnswer searchStreaming(Patient patient, String question, Consumer<String> tokenConsumer,
			Consumer<String> reasoningConsumer, Consumer<List<RecordReference>> citationsConsumer) {
		return searchStreaming(patient, question, tokenConsumer, reasoningConsumer);
	}

	/**
	 * Streaming variant that additionally hands the caller the <em>complete but not yet
	 * grounding-verified</em> answer the moment it exists, via {@code ungroundedAnswerConsumer} —
	 * the seam that lets the REST layer finish the user-visible response (emit its {@code done}
	 * event, persist the audit row) without waiting out the citation-grounding tail, which on
	 * CPU-only deployments adds seconds of Tier-2 LLM work after the answer is already readable.
	 *
	 * <p>The consumer contract:</p>
	 * <ul>
	 *   <li>It fires at most ONCE, after the answer and its citation references are final but
	 *       before grounding verification runs; the references it carries have {@code null}
	 *       verdicts.</li>
	 *   <li>It fires on the live inference path regardless of whether grounding is enabled —
	 *       its meaning is "the answer is complete", not "grounding will follow".</li>
	 *   <li>It does NOT fire when the implementation returns an answer that is already final —
	 *       e.g. a cached answer, whose verdicts were attached when it was first computed. A
	 *       caller that emitted nothing from the consumer must therefore fall back to treating
	 *       the returned {@link ChartAnswer} as the single, final result.</li>
	 * </ul>
	 *
	 * <p>This overload is deliberately abstract, not a default: every implementation —
	 * especially delegating wrappers like the caching router — must decide explicitly how to
	 * route the consumer. A defaulted implementation that silently dropped it would re-create
	 * the consumer-loss bug class that the citations channel hit before (see the history on the
	 * five-arg overload).</p>
	 *
	 * @param ungroundedAnswerConsumer called at most once with the complete answer whose
	 *        references carry no grounding verdicts yet; not called for already-final answers
	 * @return the complete answer with grounded source references, exactly as the five-arg
	 *         overload returns
	 */
	ChartAnswer searchStreaming(Patient patient, String question, Consumer<String> tokenConsumer,
			Consumer<String> reasoningConsumer, Consumer<List<RecordReference>> citationsConsumer,
			Consumer<ChartAnswer> ungroundedAnswerConsumer);

	/**
	 * Streaming variant that additionally routes the progressive-reasoning PREVIEW pass's reasoning
	 * to {@code preliminaryReasoningConsumer} — a separate channel from {@code reasoningConsumer} —
	 * so a caller can render it as provisional (clearly an in-progress preview, not the answer) and
	 * replace it the moment the committed full-chart reasoning begins arriving on
	 * {@code reasoningConsumer}. Only fires when
	 * {@code chartsearchai.progressiveReasoning.enabled} is on (otherwise the preliminary channel is
	 * never called and this behaves exactly like the six-arg overload).
	 *
	 * <p>The default delegates to the six-arg overload, which routes any preview reasoning to
	 * {@code reasoningConsumer} (merged, not separated) — so an implementation that does not override
	 * this still SHOWS preview reasoning, it just does not split it onto its own channel. Concrete
	 * streaming implementations and delegating wrappers (the caching router) override this to route
	 * the preliminary channel explicitly, the same discipline the six-arg overload's abstractness
	 * enforces for the ungrounded-answer channel.
	 *
	 * <p><strong>Override discipline:</strong> an implementation whose six-arg overload delegates
	 * <em>up</em> to this seven-arg (as the inference service and the caching router do) MUST also
	 * override this seven-arg — relying on this default while the six-arg delegates up would recurse
	 * (default → six-arg → this default → …).
	 *
	 * @param preliminaryReasoningConsumer called with each preview-reasoning fragment; never called
	 *        when progressive reasoning is off or no relevant records are found
	 */
	default ChartAnswer searchStreaming(Patient patient, String question, Consumer<String> tokenConsumer,
			Consumer<String> reasoningConsumer, Consumer<List<RecordReference>> citationsConsumer,
			Consumer<ChartAnswer> ungroundedAnswerConsumer, Consumer<String> preliminaryReasoningConsumer) {
		return searchStreaming(patient, question, tokenConsumer, reasoningConsumer, citationsConsumer,
				ungroundedAnswerConsumer);
	}

	/**
	 * Pre-warm any patient-specific caches (serialized chart, LLM prompt cache) so the
	 * first real query on this patient does not pay cold-start cost. Implementations
	 * that don't support warmup may return immediately. Callers should treat this as
	 * fire-and-forget — failures must not propagate.
	 *
	 * @param patient the patient whose chart to warm up
	 */
	default void warmup(Patient patient) {
	}

	/**
	 * As {@link #warmup(Patient)} but, when {@code pin} is true, marks the persisted KV entry as
	 * pinned — exempt from the LRU cap ({@code kvCacheMaxEntries}) — so the prewarm bootstrap can
	 * build a durable warm corpus that the ad-hoc chart-open/query pool will not evict. The default
	 * ignores {@code pin} and delegates to {@link #warmup(Patient)} for implementations that don't
	 * persist KV.
	 *
	 * @param patient the patient whose chart to warm up
	 * @param pin true to exempt the saved entry from cap-based eviction (prewarm-bootstrap corpus)
	 */
	default void warmup(Patient patient, boolean pin) {
		warmup(patient);
	}

	/**
	 * Whether this service keeps an answer cache that is currently active. Only the caching router
	 * returns {@code true}; a plain inference service has no cache. Lets the chart-write event
	 * listener decide whether a chart write needs to invalidate anything <em>before</em> resolving the
	 * affected patient, so the cache-off hot path skips that work. Default: no cache.
	 *
	 * @return {@code true} if a repeated identical query may currently be served from cache
	 */
	default boolean isCacheEnabled() {
		return false;
	}

	/**
	 * Evict any cached answers for one patient after their chart changes, so a repeated identical
	 * question recomputes against the new chart instead of serving a stale answer. A no-op for
	 * implementations without a cache. Called (via {@code IndexingHelper.onChartWrite}) when a core
	 * service event reports a chart write, regardless of which retrieval backend is active.
	 *
	 * @param patientUuid the uuid of the patient whose cached answers to drop
	 */
	default void invalidatePatient(String patientUuid) {
	}

	/**
	 * An answer to a chart search question with source citations.
	 */
	class ChartAnswer {

		private final String answer;

		private final List<RecordReference> references;

		private final int inputTokens;

		private final int outputTokens;

		private final int cachedTokens;

		private final List<SafetyWarning> safetyWarnings;

		private final String searchMode;

		private final ChartSearchAiUtils.ReferenceSlice referenceSlice;

		private final PairChipExtent pairChipExtent;

		public ChartAnswer(String answer, List<RecordReference> references) {
			this(answer, references, 0, 0, 0);
		}

		public ChartAnswer(String answer, List<RecordReference> references,
				int inputTokens, int outputTokens) {
			this(answer, references, inputTokens, outputTokens, 0);
		}

		public ChartAnswer(String answer, List<RecordReference> references,
				int inputTokens, int outputTokens, int cachedTokens) {
			this(answer, references, inputTokens, outputTokens, cachedTokens,
					java.util.Collections.<SafetyWarning> emptyList());
		}

		public ChartAnswer(String answer, List<RecordReference> references,
				int inputTokens, int outputTokens, int cachedTokens,
				List<SafetyWarning> safetyWarnings) {
			this(answer, references, inputTokens, outputTokens, cachedTokens, safetyWarnings, null);
		}

		public ChartAnswer(String answer, List<RecordReference> references,
				int inputTokens, int outputTokens, int cachedTokens,
				List<SafetyWarning> safetyWarnings, String searchMode) {
			this(answer, references, inputTokens, outputTokens, cachedTokens, safetyWarnings, searchMode,
					null);
		}

		public ChartAnswer(String answer, List<RecordReference> references,
				int inputTokens, int outputTokens, int cachedTokens,
				List<SafetyWarning> safetyWarnings, String searchMode,
				ChartSearchAiUtils.ReferenceSlice referenceSlice) {
			this(answer, references, inputTokens, outputTokens, cachedTokens, safetyWarnings, searchMode,
					referenceSlice, null);
		}

		public ChartAnswer(String answer, List<RecordReference> references,
				int inputTokens, int outputTokens, int cachedTokens,
				List<SafetyWarning> safetyWarnings, String searchMode,
				ChartSearchAiUtils.ReferenceSlice referenceSlice, PairChipExtent pairChipExtent) {
			this.answer = answer;
			this.references = java.util.Collections.unmodifiableList(
					new java.util.ArrayList<>(references));
			this.inputTokens = inputTokens;
			this.outputTokens = outputTokens;
			this.cachedTokens = cachedTokens;
			this.safetyWarnings = java.util.Collections.unmodifiableList(
					new java.util.ArrayList<>(safetyWarnings == null
							? java.util.Collections.<SafetyWarning> emptyList() : safetyWarnings));
			this.searchMode = searchMode;
			this.referenceSlice = referenceSlice;
			this.pairChipExtent = pairChipExtent;
		}

		/**
		 * The response text, which may contain numbered citation labels in brackets
		 * (e.g. [1], [3]).
		 */
		public String getAnswer() {
			return answer;
		}

		/**
		 * The ordered list of record references cited in the answer.
		 */
		public List<RecordReference> getReferences() {
			return references;
		}

		/**
		 * The number of input (prompt) tokens used.
		 */
		public int getInputTokens() {
			return inputTokens;
		}

		/**
		 * The number of output (completion) tokens used.
		 */
		public int getOutputTokens() {
			return outputTokens;
		}

		/**
		 * The number of input tokens that were served from llama-server's prompt cache
		 * (i.e., reused from a prior request's KV) instead of being processed fresh.
		 */
		public int getCachedTokens() {
			return cachedTokens;
		}

		/**
		 * Non-blocking drug-safety advisories raised by the post-answer validator
		 * (overdose / interaction / contraindication). Empty when the drug-reference
		 * feature is disabled or nothing was flagged. These annotate the answer; they
		 * never alter or suppress it.
		 */
		public List<SafetyWarning> getSafetyWarnings() {
			return safetyWarnings;
		}

		/**
		 * How the prompt's chart context was assembled for this answer — one of the
		 * {@link ChartSearchAiConstants}{@code .SEARCH_MODE_*} values, and what the audit log's
		 * {@code search_mode} column records.
		 *
		 * <p>The producer states it, so the consumer derives nothing: issue #178 was the REST layer
		 * branching on the preFilter global property at both of its audit-write sites, which left
		 * {@code queryScoped} — the shipped default — unable to appear in the column at all. It
		 * belongs on the answer because the answer is what a chart mode produced; anything that
		 * re-reads a global property afterwards can disagree with the read that built the chart.
		 *
		 * @return the mode, never null — {@link ChartSearchAiConstants#SEARCH_MODE_UNKNOWN} when the
		 *         producer stated none, so a caller writing a NOT NULL column has a value and no
		 *         caller has to invent one
		 */
		public String getSearchMode() {
			return searchMode == null ? ChartSearchAiConstants.SEARCH_MODE_UNKNOWN : searchMode;
		}

		/**
		 * How much module-supplied reference material the prompt behind this answer carried — the
		 * record count and character total the audit row's {@code reference_slice_records} and
		 * {@code reference_slice_chars} columns record (issue #229).
		 *
		 * <p>The producer states it and the consumer derives nothing, the same discipline
		 * {@link #getSearchMode()} follows and for the same reason: the number is a property of the
		 * chart that was actually assembled, and anything re-deriving it afterwards is measuring a
		 * different chart. {@code LlmInferenceService} resolves it once per method, off the chart
		 * {@code DrugReferenceInjector.inject} returned, and sets it on every answer that method
		 * produces — including the ungrounded one the streaming path hands its consumer, because the
		 * two audit shapes read different objects.
		 *
		 * <p><b>Null is not zero.</b> Zero is a real measurement — the prompt carried no reference
		 * material — while null says the producer stated nothing at all, which is what the five
		 * constructors above do. Collapsing null into zero would make an unmeasured row
		 * indistinguishable from a measured empty one, which is the failure issue #178 fixed for the
		 * mode column; the audit columns are nullable for exactly this reason. There is no
		 * {@code UNKNOWN} sentinel to return instead because those columns, unlike
		 * {@code search_mode}, are not NOT NULL.
		 *
		 * <p><b>Zero says what the prompt carried, never why.</b> It is a true reading in every case —
		 * the prompt really did carry no reference material — which is why no third value is owed here
		 * the way {@code PatientClinicalContext.contraindicationRecordsRead()} is owed one: that
		 * exists because a chart the module could not read is not a chart that records nothing,
		 * whereas a prompt that carried nothing did carry nothing. What it will not tell you is which
		 * of several quite different situations produced it — the question matched no reference entry;
		 * {@code chartsearchai.drugReference.enabled} is off, which is the SHIPPED DEFAULT
		 * ({@link ChartSearchAiConstants#DEFAULT_DRUG_REFERENCE_ENABLED}), so a stock install reads
		 * 0/0 on every row; some combination of {@code drugReference.injectFromQuery},
		 * {@code drugReference.injectFromOrders} and {@code drugSafety.validateAnswers} is off — note
		 * the third is a {@code drugSafety} property rather than a {@code drugReference} one, and that
		 * none of the three silences this number on its own, each leaving another arm injecting;
		 * {@code DrugReferenceInjector.inject} threw and returned the chart unmodified, which it does
		 * deliberately so an enrichment can never break the answer path; or the injector rebuilt the
		 * chart with active-order records alone, which are the patient's own and outside this number.
		 * Do not read that list as complete — it is the paths visible from {@code inject} and
		 * {@code injectRecords} today, and an earlier version of this javadoc claimed there were three
		 * when a count was never checked. The operational point does not depend on the count: a column
		 * of zeros is not evidence a corpus raises no reference material, and the injector's own log
		 * is the only thing that separates a swallowed failure from an honest miss.
		 *
		 * <p><b>On a cache hit this states the ORIGINAL request's slice.</b>
		 * {@code ChartSearchServiceRouter} returns the cached {@code ChartAnswer} unchanged, so the
		 * row files the prompt the answer was actually built from — which is the truthful reading for
		 * one row, and means an operator SUMMING the column across rows over-reports prompt spend by
		 * every cache hit. That is inherited from how caching works here rather than chosen, and it
		 * matches what {@code search_mode} already does.
		 *
		 * <p>It counts reference-group records only, so the {@code active_drug_order} records the
		 * injector also writes are outside it — they are the patient's own prescriptions and group as
		 * chart evidence. Their count remains on the injector's DEBUG line.
		 *
		 * @return the slice, or null when the producer stated none
		 */
		public ChartSearchAiUtils.ReferenceSlice getReferenceSlice() {
			return referenceSlice;
		}

		/**
		 * How many drug pairs this answer's PAIRWISE interaction check found and how many of them it
		 * reported — what the {@code interactionPairs} key on the {@code /search} response and on the
		 * {@code done} and {@code grounded} SSE events publishes (issue
		 * <a href="https://github.com/openmrs/openmrs-module-chartsearchai/issues/336">#336</a>).
		 *
		 * <p>The producer states it, so no consumer derives it. A capped list was otherwise
		 * indistinguishable from a complete one everywhere but a server-side WARN, and the chip count
		 * cannot stand in for it: the drug-in-play arm raises interaction chips for drugs only the
		 * ANSWER named and class chips this counts nowhere, so counting them answers a different
		 * question. That arm states this too since issue
		 * <a href="https://github.com/openmrs/openmrs-module-chartsearchai/issues/356">#356</a>, for
		 * the one-drug prescribing question neither pairwise arm runs on.
		 *
		 * @return the statement, or {@code null} where the interaction check made none —
		 *         {@link PairChipExtent} is canonical for what that covers, and for why {@code null}
		 *         is not zero
		 */
		public PairChipExtent getPairChipExtent() {
			return pairChipExtent;
		}
	}

	/**
	 * Identifies a source record in OpenMRS cited by the LLM answer.
	 */
	class RecordReference {

		private final int index;

		private final String resourceType;

		private final String resourceUuid;

		private final Date date;

		private final Boolean grounded;

		private final String source;

		private final int withheldInteractions;

		public RecordReference(int index, String resourceType, String resourceUuid, Date date) {
			this(index, resourceType, resourceUuid, date, null);
		}

		public RecordReference(int index, String resourceType, String resourceUuid, Date date, Boolean grounded) {
			this(index, resourceType, resourceUuid, date, grounded, null, 0);
		}

		/**
		 * Full constructor, carrying the citation metadata a client renders beside the reference —
		 * see {@link #getSource()} and {@link #getWithheldInteractions()}. The shorter constructors
		 * default both to "none", which is a chart record's real shape.
		 */
		public RecordReference(int index, String resourceType, String resourceUuid, Date date, Boolean grounded,
				String source, int withheldInteractions) {
			this.index = index;
			this.resourceType = resourceType;
			this.resourceUuid = resourceUuid;
			this.date = date;
			this.grounded = grounded;
			this.source = source;
			this.withheldInteractions = withheldInteractions;
		}

		public int getIndex() {
			return index;
		}

		public String getResourceType() {
			return resourceType;
		}

		public String getResourceUuid() {
			return resourceUuid;
		}

		public Date getDate() {
			return date;
		}

		/**
		 * Whether the cited record was found to actually support the answer
		 * sentence(s) that cite it. {@code TRUE}/{@code FALSE} when grounding
		 * verification ran (see {@code chartsearchai.grounding.enabled});
		 * {@code null} when verification was disabled, could not run for this
		 * reference (e.g. the record carried no text to compare against), or ran
		 * and could not certify it — a citation of a compound claim unit under
		 * entailment (issue #302), a chart citation whose claim also rests on
		 * module-supplied reference material and whose judge said no (issue
		 * #284), or a {@code reference}-group citation whose Tier-1 cosine
		 * PASSED. A reference-group cosine FAIL is kept and returns
		 * {@code FALSE} here; only the wire withholds it unconditionally, which
		 * is the distinction the next paragraph draws — and note the #284 case
		 * is unlike both, withheld INSIDE the verifier, so no verdict survives
		 * here to read. Its count is logged once per answer instead. A
		 * {@code null} verdict must be rendered as "unverified", never as
		 * "verified".
		 *
		 * <p>This is the verdict the pipeline holds, which is not always the one
		 * a client sees: for a {@code reference}-group citation the REST layer
		 * publishes {@code null} whatever this returns (issue #201, see
		 * {@code ChartSearchAiRestController.groundedForWire}). Read this to
		 * reason about grounding inside the module; read the wire to reason
		 * about what a client renders.
		 */
		public Boolean getGrounded() {
			return grounded;
		}

		/**
		 * Provenance for this citation — the dataset an injected reference record came from,
		 * {@code null} for a chart record (see
		 * {@link org.openmrs.module.chartsearchai.serializer.PatientChartSerializer.RecordMapping#getSource()}).
		 * Carried as a field precisely so it does not have to be inside the record text, where
		 * the model quoted it into the answer (issue #117).
		 */
		public String getSource() {
			return source;
		}

		/**
		 * How many interaction partners the cited record does not show, so a client can say the
		 * citation shows a subset — not that they were omitted for length, which is usually not why.
		 * 0 when it shows them all. See
		 * {@link org.openmrs.module.chartsearchai.serializer.PatientChartSerializer.RecordMapping#getWithheldInteractions()}.
		 */
		public int getWithheldInteractions() {
			return withheldInteractions;
		}

		/**
		 * @return a copy of this reference carrying the given grounding verdict
		 */
		public RecordReference withGrounded(Boolean verdict) {
			return new RecordReference(index, resourceType, resourceUuid, date, verdict, source,
					withheldInteractions);
		}
	}
}
